/// Helpers para construir URLs del CDN imagin.studio.
class CarImageService {
  CarImageService._();

  static const String _baseUrl = 'https://cdn.imagin.studio/getimage';
  static const String _customer = 'img';

  static String buildUrl({
    required String make,
    required String model,
    required int year,
  }) {
    final makeSlug = _makeSlug(make);
    final modelSlug = _modelSlug(make, model);
    return '$_baseUrl'
        '?customer=$_customer'
        '&make=$makeSlug'
        '&modelFamily=$modelSlug'
        '&modelYear=$year'
        '&angle=29'
        '&zoomType=fullscreen';
  }

  // ── Make slugs ───────────────────────────────────────────────────────────────

  static const Map<String, String> _makeOverrides = {
    'Mercedes':    'mercedes-benz',
    'Land Rover':  'land-rover',
    'Alfa Romeo':  'alfa-romeo',
    'Aston Martin':'aston-martin',
    'SEAT':        'seat',
    'Citroën':     'citroen',
    'Genesis':     'genesis',
    'MG':          'mg',
    'Haval':       'haval',
    'Chery':       'chery',
    'JAC':         'jac',
  };

  static String _makeSlug(String make) =>
      _makeOverrides[make] ?? make.toLowerCase().replaceAll(' ', '-');

  // ── Model slugs ──────────────────────────────────────────────────────────────

  static const Map<String, Map<String, String>> _modelOverrides = {
    'BMW': {
      'Serie 1': '1-series',
      'Serie 2': '2-series',
      'Serie 3': '3-series',
      'Serie 4': '4-series',
      'Serie 5': '5-series',
      'Serie 6': '6-series',
      'Serie 7': '7-series',
      'Serie 8': '8-series',
      'M2': 'm2',
      'M3': 'm3',
      'M4': 'm4',
      'M5': 'm5',
      'M8': 'm8',
      'X1': 'x1',
      'X2': 'x2',
      'X3': 'x3',
      'X4': 'x4',
      'X5': 'x5',
      'X6': 'x6',
      'X7': 'x7',
      'i4': 'i4',
      'i5': 'i5',
      'i7': 'i7',
      'iX': 'ix',
    },
    'Mercedes': {
      'Clase A':  'a-class',
      'Clase B':  'b-class',
      'Clase C':  'c-class',
      'Clase E':  'e-class',
      'Clase S':  's-class',
      'CLA':      'cla',
      'GLA':      'gla',
      'GLB':      'glb',
      'GLC':      'glc',
      'GLE':      'gle',
      'GLS':      'gls',
      'AMG GT':   'amg-gt',
    },
    'Audi': {
      'A1': 'a1',
      'A3': 'a3',
      'A4': 'a4',
      'A5': 'a5',
      'A6': 'a6',
      'A8': 'a8',
      'RS3': 'rs3',
      'RS6': 'rs6',
      'TT': 'tt',
      'Q2': 'q2',
      'Q3': 'q3',
      'Q5': 'q5',
      'Q7': 'q7',
      'Q8': 'q8',
      'e-tron': 'e-tron',
    },
    'Volkswagen': {
      'Polo':       'polo',
      'Golf':       'golf',
      'Golf GTI':   'golf',
      'Jetta':      'jetta',
      'Passat':     'passat',
      'Arteon':     'arteon',
      'T-Cross':    't-cross',
      'T-Roc':      't-roc',
      'Tiguan':     'tiguan',
      'Touareg':    'touareg',
      'ID.3':       'id3',
      'ID.4':       'id4',
    },
    'Porsche': {
      '911':         '911',
      '718 Boxster': '718-boxster',
      '718 Cayman':  '718-cayman',
      'Panamera':    'panamera',
      'Macan':       'macan',
      'Cayenne':     'cayenne',
      'Taycan':      'taycan',
    },
    'Toyota': {
      'Yaris':               'yaris',
      'Yaris Cross':         'yaris-cross',
      'Corolla':             'corolla',
      'Corolla Cross':       'corolla-cross',
      'Camry':               'camry',
      'C-HR':                'c-hr',
      'RAV4':                'rav4',
      'Hilux':               'hilux',
      'Land Cruiser':        'land-cruiser',
      'Land Cruiser Prado':  'land-cruiser-prado',
      'Fortuner':            'fortuner',
      'Rush':                'rush',
      'Innova':              'innova',
      'GR86':                'gr86',
      'GR Supra':            'supra',
      'Prius':               'prius',
      'Highlander':          'highlander',
    },
    'Honda': {
      'Jazz':          'jazz',
      'Civic':         'civic',
      'Civic Type R':  'civic',
      'Accord':        'accord',
      'City':          'city',
      'HR-V':          'hr-v',
      'CR-V':          'cr-v',
      'Pilot':         'pilot',
      'Passport':      'passport',
      'Ridgeline':     'ridgeline',
    },
    'Mazda': {
      'Mazda 2': 'mazda2',
      'Mazda 3': 'mazda3',
      'Mazda 6': 'mazda6',
      'CX-3':    'cx-3',
      'CX-30':   'cx-30',
      'CX-5':    'cx-5',
      'CX-9':    'cx-9',
      'MX-5':    'mx-5',
      'MX-30':   'mx-30',
    },
    'Subaru': {
      'Impreza':   'impreza',
      'WRX':       'wrx',
      'BRZ':       'brz',
      'Legacy':    'legacy',
      'Outback':   'outback',
      'Forester':  'forester',
      'Crosstrek': 'crosstrek',
      'Ascent':    'ascent',
    },
    'Mitsubishi': {
      'Eclipse Cross': 'eclipse-cross',
      'Outlander':     'outlander',
      'ASX':           'asx',
      'Pajero Sport':  'pajero-sport',
      'L200':          'l200',
    },
    'Suzuki': {
      'Swift':       'swift',
      'Swift Sport': 'swift',
      'Baleno':      'baleno',
      'S-Cross':     's-cross',
      'Vitara':      'vitara',
      'Jimny':       'jimny',
      'Grand Vitara':'grand-vitara',
    },
    'Ford': {
      'Puma':          'puma',
      'Fiesta':        'fiesta',
      'Focus':         'focus',
      'Focus ST':      'focus',
      'Focus RS':      'focus',
      'Mustang':       'mustang',
      'Mustang Mach-E':'mustang-mach-e',
      'Kuga':          'kuga',
      'Explorer':      'explorer',
      'Bronco':        'bronco',
      'Edge':          'edge',
      'Expedition':    'expedition',
      'F-150':         'f-150',
      'Ranger':        'ranger',
      'Maverick':      'maverick',
      'S-Max':         's-max',
    },
    'Chevrolet': {
      'Spark':      'spark',
      'Cruze':      'cruze',
      'Malibu':     'malibu',
      'Camaro':     'camaro',
      'Corvette':   'corvette',
      'Trax':       'trax',
      'Trailblazer':'trailblazer',
      'Blazer':     'blazer',
      'Equinox':    'equinox',
      'Traverse':   'traverse',
      'Tahoe':      'tahoe',
      'Suburban':   'suburban',
      'Colorado':   'colorado',
      'Silverado':  'silverado',
    },
    'Hyundai': {
      'Grand i10':  'grand-i10',
      'i10':        'i10',
      'i20':        'i20',
      'i30':        'i30',
      'i30 N':      'i30',
      'Accent':     'accent',
      'Elantra':    'elantra',
      'Sonata':     'sonata',
      'Venue':      'venue',
      'Creta':      'creta',
      'Kona':       'kona',
      'Tucson':     'tucson',
      'Santa Fe':   'santa-fe',
      'Palisade':   'palisade',
      'Stargazer':  'stargazer',
      'Ioniq 5':    'ioniq-5',
      'Ioniq 6':    'ioniq-6',
    },
    'Kia': {
      'Picanto':   'picanto',
      'Rio':       'rio',
      'Cerato':    'cerato',
      'K5':        'k5',
      'Stinger':   'stinger',
      'Sonet':     'sonet',
      'Seltos':    'seltos',
      'Stonic':    'stonic',
      'Niro':      'niro',
      'Sportage':  'sportage',
      'Sorento':   'sorento',
      'Telluride': 'telluride',
      'Carnival':  'carnival',
      'EV6':       'ev6',
    },
    'Nissan': {
      'March':     'march',
      'Note':      'note',
      'Versa':     'versa',
      'Sentra':    'sentra',
      'Altima':    'altima',
      'Maxima':    'maxima',
      'Kicks':     'kicks',
      'Juke':      'juke',
      'Qashqai':   'qashqai',
      'Murano':    'murano',
      'X-Trail':   'x-trail',
      'Pathfinder':'pathfinder',
      'Terra':     'terra',
      'Armada':    'armada',
      'Frontier':  'frontier',
      'Navara':    'navara',
      'GT-R':      'gt-r',
      'Z':         'z',
    },
    'Renault': {
      'Twingo':       'twingo',
      'Clio':         'clio',
      'Sandero':      'sandero',
      'Logan':        'logan',
      'Megane':       'megane',
      'Megane E-Tech':'megane-e-tech',
      'Captur':       'captur',
      'Duster':       'duster',
      'Arkana':       'arkana',
      'Kadjar':       'kadjar',
      'Koleos':       'koleos',
    },
    'Peugeot': {
      '108':     '108',
      '208':     '208',
      '308':     '308',
      '408':     '408',
      '508':     '508',
      '2008':    '2008',
      '3008':    '3008',
      '5008':    '5008',
      'Rifter':  'rifter',
    },
    'Citroën': {
      'C1':          'c1',
      'C3':          'c3',
      'C3 Aircross': 'c3-aircross',
      'C4':          'c4',
      'C5 X':        'c5-x',
      'C5 Aircross': 'c5-aircross',
      'Berlingo':    'berlingo',
    },
    'Opel': {
      'Corsa':     'corsa',
      'Astra':     'astra',
      'Insignia':  'insignia',
      'Mokka':     'mokka',
      'Grandland': 'grandland',
      'Crossland': 'crossland',
    },
    'Fiat': {
      '500':   '500',
      '500X':  '500x',
      'Panda': 'panda',
      'Tipo':  'tipo',
    },
    'Alfa Romeo': {
      'Giulia':                  'giulia',
      'Giulia Quadrifoglio':     'giulia',
      'Stelvio':                 'stelvio',
      'Stelvio Quadrifoglio':    'stelvio',
      'Tonale':                  'tonale',
    },
    'Skoda': {
      'Fabia':     'fabia',
      'Octavia':   'octavia',
      'Octavia RS':'octavia',
      'Superb':    'superb',
      'Karoq':     'karoq',
      'Kodiaq':    'kodiaq',
      'Enyaq':     'enyaq',
    },
    'SEAT': {
      'Ibiza':   'ibiza',
      'Leon':    'leon',
      'Leon ST': 'leon',
      'Arona':   'arona',
      'Ateca':   'ateca',
      'Tarraco': 'tarraco',
    },
    'Volvo': {
      'XC40': 'xc40',
      'XC60': 'xc60',
      'XC90': 'xc90',
      'S60':  's60',
      'V60':  'v60',
      'V90':  'v90',
      'C40':  'c40',
    },
    'Land Rover': {
      'Defender 90':         'defender',
      'Defender 110':        'defender',
      'Discovery':           'discovery',
      'Discovery Sport':     'discovery-sport',
      'Range Rover':         'range-rover',
      'Range Rover Sport':   'range-rover-sport',
      'Range Rover Evoque':  'range-rover-evoque',
      'Range Rover Velar':   'range-rover-velar',
    },
    'Jeep': {
      'Renegade':       'renegade',
      'Compass':        'compass',
      'Cherokee':       'cherokee',
      'Grand Cherokee': 'grand-cherokee',
      'Wrangler':       'wrangler',
      'Gladiator':      'gladiator',
    },
    'Dodge': {
      'Challenger': 'challenger',
      'Charger':    'charger',
      'Durango':    'durango',
    },
    'Tesla': {
      'Model 3':    'model-3',
      'Model S':    'model-s',
      'Model X':    'model-x',
      'Model Y':    'model-y',
      'Cybertruck': 'cybertruck',
    },
    'Jaguar': {
      'XE':    'xe',
      'XF':    'xf',
      'XJ':    'xj',
      'F-Type':'f-type',
      'E-Pace':'e-pace',
      'F-Pace':'f-pace',
      'I-Pace':'i-pace',
    },
    'Genesis': {
      'G70':  'g70',
      'G80':  'g80',
      'G90':  'g90',
      'GV70': 'gv70',
      'GV80': 'gv80',
      'GV60': 'gv60',
    },
    'MG': {
      'MG3':     'mg3',
      'MG5':     'mg5',
      'MG6':     'mg6',
      'ZS':      'zs',
      'ZS EV':   'zs',
      'HS':      'hs',
      'RX5':     'rx5',
      'Marvel R':'marvel-r',
    },
    'Lexus': {
      'UX': 'ux',
      'NX': 'nx',
      'RX': 'rx',
      'GX': 'gx',
      'LX': 'lx',
      'IS': 'is',
      'ES': 'es',
      'GS': 'gs',
      'LS': 'ls',
      'LC': 'lc',
    },
    'Infiniti': {
      'Q50':  'q50',
      'Q60':  'q60',
      'QX50': 'qx50',
      'QX60': 'qx60',
      'QX80': 'qx80',
    },
  };

  static String _modelSlug(String make, String model) {
    final override = _modelOverrides[make]?[model];
    if (override != null) return override;
    return model.toLowerCase().replaceAll(' ', '-').replaceAll('/', '-');
  }

  /// Returns a CDN URL using the first known model for [make] as a brand fallback.
  /// Returns null if the make is completely unknown (e.g. custom make).
  static String? buildBrandFallbackUrl({required String make, required int year}) {
    final models = _modelOverrides[make];
    if (models == null || models.isEmpty) return null;
    final firstSlug = models.values.first;
    final makeSlug = _makeSlug(make);
    return '$_baseUrl'
        '?customer=$_customer'
        '&make=$makeSlug'
        '&modelFamily=$firstSlug'
        '&modelYear=$year'
        '&angle=29'
        '&zoomType=fullscreen';
  }
}
